artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://rohithprojectstorage.blob.core.windows.net/birddataset/bird-dataset.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  training_data_path: artifacts/data_ingestion/train
  validation_data_path: artifacts/data_ingestion/valid

evaluation:
  test_data_path: artifacts/data_ingestion/test

prediction:
  data_file_path: artifacts/data_ingestion/birds.csv
  labels_column_name: labels

get_trained_model:
  root_dir: artifacts/training
  source: "https://rohithprojectstorage.blob.core.windows.net/birdmodel/model.zip"
  local_data_file: artifacts/training/model.zip
  unzip_dir: artifacts/training